modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-v3"
[[mods]]
modId = "sverve_hud_check"
version = "1.0.0"
displayName = "Sverve HUD runtime check"
[[dependencies.sverve_hud_check]]
modId = "sverve"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "CLIENT"
