modLoader = "javafml"
loaderVersion = "[4,)"
license = "LGPL-v3"
[[mods]]
modId = "sverve_lifecycle_check"
version = "1.0.0"
displayName = "Sverve server lifecycle check"
[[dependencies.sverve_lifecycle_check]]
modId = "sverve"
type = "required"
versionRange = "[1,)"
ordering = "AFTER"
side = "SERVER"
